version: '3.8'
services:
  musica-db:
    image: mongo:latest
    container_name: musica-db
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - ./tmp/mongodb_data:/data/db

volumes:
  mongodb_data:
    name: musica-db-data
