export const ActionTypes = {
  PAUSE_MUSIC: 'PAUSE_MUSIC',
  PLAY_MUSIC: 'PLAY_MUSIC',
  NEXT_MUSIC: 'NEXT_MUSIC',
  PREV_MUSIC: 'PREV_MUSIC',
  SELECT_MUSIC: 'SELECT_MUSIC',
  CLEAR_ALL_MUSICS: 'CLEAR_ALL_MUSICS',
  ADD_MUSIC: 'ADD_MUSIC',
  DELETE_MUSIC: 'DELETE_MUSIC',
  EDIT_MUSIC: 'EDIT_MUSIC',
};
