name: Continuous Integration

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Use PNPM'
        run: npm install -g pnpm

      - name: 'Install Dependencies'
        run: pnpm install

      - name: Lint API
        run: npx nx lint api

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Use PNPM'
        run: npm install -g pnpm

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Production Build'
        run: npx nx build api

  test:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Use PNPM'
        run: npm install -g pnpm

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Setup MongoDB Memory Server'
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_URI
          binary-version: 7.0.0
          instance-dbName: musica-runner-test
          instance-port: 27017
          instance-storageEngine: wiredTiger
          mongoms-debug: 1

      - name: 'Unit Test API'
        run: npx nx test api
        env:
          INSIDE_ACTION_RUNNER: true

      - name: 'E2E Test API'
        run: npx nx e2e api-e2e
