name: Continuous Integration

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Use PNPM'
        run: npm install -g pnpm

      - name: 'Cache dependencies'
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  test:
    runs-on: ubuntu-latest
    needs: ['build', 'cache-dependencies', 'lint']
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Unit Test API'
        run: |
          npx nx test api

      - name: 'E2E Test API'
        run: |
          npx nx e2e api-e2e

  lint:
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Lint API
        run: |
          npx nx lint api

  build:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Production Build'
        run: npx nx api:build:production
