name: 'Chromatic'

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        run: chromaui/action@latest
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: libs/ui-shared
